name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/cpen321-tutorial"
      
      - name: Rebuild and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: PROD_MONGODB_URI,GOOGLE_CLIENT_ID,JWT_SECRET
          script: |
            cd /home/ubuntu/cpen321-tutorial
            echo "MONGODB_URI=$PROD_MONGODB_URI" > .env
            echo "PORT=80" >> .env
            echo "JWT_SECRET=$JWT_SECRET" >> .env
            echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
            docker-compose down
            docker-compose up -d --build
        env:
          PROD_MONGODB_URI: ${{ secrets.PROD_MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
