name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/cpen321-tutorial"
      
      - name: Rebuild and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: PROD_MONGODB_URI
          script: |
            cd /home/ubuntu/cpen321-tutorial
            # Write the secret into .env so docker-compose can read it
            echo "MONGODB_URI=${PROD_MONGODB_URI}" > .env
            echo "PORT=3000" >> .env
            docker-compose down
            docker-compose up -d --build
